from selenium.webdriver.common.by import By
from src.testproject.decorator import report_assertion_errors
from src.testproject.sdk.drivers.actions import Actions


"""
This pytest test was automatically generated by TestProject
    Project: Upside
    Package: TestProject.Generated.Tests.Upside
    Test: Logout
    Generated by: Christopher Wamble (cwsite.ma@gmail.com)
    Generated on 08/04/2022, 19:07:16
"""


@report_assertion_errors
def test_main(driver):
    """This test was auto generated from steps of the 'GetUpside' test."""

    # 1. Pause for '5000'ms
    # give 5 seconds for menu to load on screen
    driver.pause(milliseconds=5000)

    # 2. Click 'Navigate up'
    navigate_up = driver.find_element(By.XPATH,
                                      "//android.widget.ImageButton[@content-desc = 'Navigate up']")
    navigate_up.click()

    # 3. Click 'Profile'
    profile = driver.find_element(By.XPATH,
                                  "//android.widget.TextView[@text = 'Profile']")
    profile.click()

    # 4. Click 'com.upside.consumer.android.beta:id/i...'
    com_upside_consumer_android_beta_colon_id_slash_i_ = driver.find_element(By.ID,
                                                                             "com.upside.consumer.android.beta:id/iv_profile_more")
    com_upside_consumer_android_beta_colon_id_slash_i_.click()

    # 5. Click 'Sign out'
    sign_out = driver.find_element(By.XPATH,
                                   "//android.widget.TextView[@text = 'Sign out']")
    sign_out.click()
