from addons.visible_elements_operations import VisibleElementsOperations
from selenium.webdriver.common.by import By
from src.testproject.decorator import report_assertion_errors


"""
This pytest test was automatically generated by TestProject
    Project: Upside
    Package: TestProject.Generated.Tests.Upside
    Test: Bypass Handler
    Generated by: Christopher Wamble (cwsite.ma@gmail.com)
    Generated on 08/04/2022, 21:03:11
"""


@report_assertion_errors
def test_main(driver):
    """This test was auto generated from steps of the 'GetUpside' test."""

    # 1. Click 'Maybe later' if it's visible
    # bypass possible block screen to get to map
    maybe_later = (
        By.ID, "com.upside.consumer.android.beta:id/viewthrough_maybe_later_b")
    driver.addons().execute(
        VisibleElementsOperations.clickifvisibleandroid(
            timeout=""), *maybe_later)

    # 2. Click 'Okay' if it's visible
    # this came out of nowhere suddenly, handle sudden BP promo that appears
    okay = (By.ID, "com.upside.consumer.android.beta:id/offer_details_check_in_for_cash_back_okay_b")
    driver.addons().execute(
        VisibleElementsOperations.clickifvisibleandroid(
            timeout=""), *okay)

    # 3. Click 'com.upside.consumer.android.beta:id/o...' if it's visible
    # select back arrow in case the BP offer (or any kind of offer) reappears again.
    com_upside_consumer_android_beta_colon_id_slash_o_ = (
        By.ID, "com.upside.consumer.android.beta:id/offer_details_close_iv")
    driver.addons().execute(
        VisibleElementsOperations.clickifvisibleandroid(
            timeout=""), *com_upside_consumer_android_beta_colon_id_slash_o_)

    # 4. Click 'Not Now' if it's visible
    # bypass the request for further data
    not_now = (
        By.ID, "com.upside.consumer.android.beta:id/permissions_negative_action_b")
    driver.addons().execute(
        VisibleElementsOperations.clickifvisibleandroid(
            timeout=""), *not_now)
