from addons.visible_elements_operations import VisibleElementsOperations
from selenium.webdriver.common.by import By
from src.testproject.decorator import report_assertion_errors


"""
This pytest test was automatically generated by TestProject
    Project: Upside
    Package: TestProject.Generated.Tests.Upside
    Test: Bypass Handler
    Generated by: Christopher Wamble (cwsite.ma@gmail.com)
    Generated on 08/04/2022, 19:07:16
"""


@report_assertion_errors
def test_main(driver):
    """This test was auto generated from steps of the 'GetUpside' test."""

    # 1. Click 'Maybe later' if it's visible
    # bypass possible block screen to get to map
    maybe_later = (
        By.ID, "com.upside.consumer.android.beta:id/viewthrough_maybe_later_b")
    driver.addons().execute(
        VisibleElementsOperations.clickifvisibleandroid(
            timeout=""), *maybe_later)

    # 2. Click 'Not Now' if it's visible
    # bypass the request for further data
    not_now = (
        By.ID, "com.upside.consumer.android.beta:id/permissions_negative_action_b")
    driver.addons().execute(
        VisibleElementsOperations.clickifvisibleandroid(
            timeout=""), *not_now)
